---
# telco-ran-du-manifests tasks

- name: Create directories for hv-vm Telco RAN DU manifests on bastion
  file:
    path: "{{ item.dir }}"
    state: directory
  delegate_to: "{{ groups['bastion'][0] }}"
  run_once: true
  when: item.enabled | default(true) | bool
  loop:
  - dir: "{{ hv_vm_manifests_directory }}/"
  - dir: "{{ hv_vm_manifests_directory }}/sno"
  - dir: "{{ hv_vm_manifests_directory }}/sno/ai-siteconfig"
    enabled: "{{ create_ai_siteconfigs }}"
  - dir: "{{ hv_vm_manifests_directory }}/sno/ai-clusterinstance"
    enabled: "{{ create_ai_clusterinstances }}"
  - dir: "{{ hv_vm_manifests_directory }}/sno/ai-manifest"
    enabled: "{{ create_ai_manifests }}"
  - dir: "{{ hv_vm_manifests_directory }}/sno/ibi-clusterinstance"
    enabled: "{{ create_ibi_clusterinstances }}"
  - dir: "{{ hv_vm_manifests_directory }}/sno/ibi-manifest"
    enabled: "{{ create_ibi_manifests }}"

- name: Set pull-secret for bastion registry
  set_fact:
    pull_secret: "{{ disconnected_pull_secret }}"
  delegate_to: "{{ groups['bastion'][0] }}"
  run_once: true
  when: rhacm_disconnected_registry and rhacm_disconnected_registry|length > 1

- name: Template a manifest per hv-vm on bastion as a SNO
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  delegate_to: "{{ groups['bastion'][0] }}"
  when: item.enabled | default(true) | bool
  loop:
  # AI siteconfig/clusterinstance/manifests
  - src: ai-siteconfig.yml.j2
    dest: "{{ hv_vm_manifests_directory }}/sno/ai-siteconfig/{{ inventory_hostname }}-siteconfig.yml"
    enabled: "{{ create_ai_siteconfigs }}"
  - src: ai-resources.yml.j2
    dest: "{{ hv_vm_manifests_directory }}/sno/ai-siteconfig/{{ inventory_hostname }}-resources.yml"
    enabled: "{{ create_ai_siteconfigs }}"
  - src: ai-clusterinstance.yml.j2
    dest: "{{ hv_vm_manifests_directory }}/sno/ai-clusterinstance/{{ inventory_hostname }}-clusterinstance.yml"
    enabled: "{{ create_ai_clusterinstances }}"
  - src: ai-manifest.yml.j2
    dest: "{{ hv_vm_manifests_directory }}/sno/ai-manifest/{{ inventory_hostname }}-manifest.yml"
    enabled: "{{ create_ai_manifests }}"

  # IBI clusterinstance / manifests
  - src: ibi-clusterinstance.yml.j2
    dest: "{{ hv_vm_manifests_directory }}/sno/ibi-clusterinstance/{{ inventory_hostname }}-clusterinstance.yml"
    enabled: "{{ create_ibi_clusterinstances }}"
  - src: ibi-manifest.yml.j2
    dest: "{{ hv_vm_manifests_directory }}/sno/ibi-manifest/{{ inventory_hostname }}-manifest.yml"
    enabled: "{{ create_ibi_manifests }}"
