---
# telco-core-manifests default vars

# Provide pull-secret for connected manifests
pull_secret: "{{ lookup('file', '../pull-secret.txt') }}"

# Disconnected registry pull secret
auth_encoded: "{{ (registry_user + ':' + registry_password) | b64encode }}"
disconnected_pull_secret: '{"auths": {"{{ rhacm_disconnected_registry }}:{{ rhacm_disconnected_registry_port }}": {"auth": "{{ auth_encoded }}"}}}'

ssh_public_key_file: ~/.ssh/id_rsa.pub

telco_core_clusterinstance_extra_manifests: false
telco_core_clusterinstance_custom_manifests: false

# Manifest must exist in acm-deploy-load directory in order to be added to the extra-manifests configmap
telco_core_extra_manifests:
# - control-plane-load-kernel-modules.yaml
- 4.20-newer/control-plane-load-kernel-modules.yaml
- kdump-master.yaml
- kdump-worker.yaml
- mc_rootless_pods_selinux.yaml
- mount_namespace_config_master.yaml
- mount_namespace_config_worker.yaml
- sctp_module_mc.yaml
# - worker-load-kernel-modules.yaml
- 4.20-newer/worker-load-kernel-modules.yaml

# Enable observability for Telco Core clusters
telco_core_observability: true

# Defaults for AI clusterinstance templates
# Adjusted for search collector enabled (ai-cluster-templates-v1-search), original (ai-cluster-templates-v1)
telco_core_ai_clusterinstance_cluster_templates_ns: open-cluster-management
telco_core_ai_clusterinstance_cluster_templates: ai-cluster-templates-v1-search
telco_core_ai_clusterinstance_node_templates_ns: open-cluster-management
telco_core_ai_clusterinstance_node_templates: ai-node-templates-v1
