---
apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: local-disks
  namespace: "openshift-local-storage"
spec:
  logLevel: Normal
  managementState: Managed
  storageClassDevices:
    # The list of storage classes and associated devicePaths need to be specified like this example:
    # The devicePaths below must be adjusted to the hardware.
    # For stability and reliability, it's recommended to use persistent
    # naming conventions for devicePaths, such as /dev/disk/by-path.
    - devicePaths:
      - /dev/disk/by-path/pci-0000:05:00.0-nvme-1
      fsType: xfs
      storageClassName: example-storage-class
      volumeMode: Filesystem
