apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
#- telco-core-siteconfig.yml

resources:
#- standard-00001-clusterinstance.yml
#- telco-core-clusterinstance.yml
#- telco-core-resources.yml
