apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
- core-baseline.yaml
- core-overlay.yaml
{% if telco_core_profile_version is version('4.20', '>=') %}
# - core-finish.yaml
{% endif %}
# - core-upgrade.yaml

resources:
- ns.yaml
- template-values/regional.yaml
- template-values/hw-types.yaml
